subtask/KAH-1468 (Update sample notificator plugin with new structure)
Kaholo/slack-notification-plugin pull request #1
Opened 2021-09-01 13:38 UTC by kbuchacz

2021-09-01 18:09 UTC, sielakos approved these changes

2021-09-02 06:22 UTC, davvvid1 requested changes

2021-09-02 06:22 UTC, davvvid1 commented on src/index.js
> +        Agent: ${pipeline.agentName}
I would add pipeline status to the message. It might be useful for our testing/debugging purposes.

2021-09-02 07:17 UTC, davvvid1 approved these changes

2021-09-02 07:17 UTC, merged